### ISSUE TITLE
Packing Models

### ISSUE THREAD

**Issue by Throwaway132** [LagoLunatic/ww_model_helpers#1]
I can't for the life of me figure out how to layout the folders when packing models, I have both the 'Link Original' and 'Custom Model' in the same folder but I keep getting the error "Invalid Arguments. proper format: pack_player -link "Path/to/clean/link/folder" -custom "Path/to/Custom/Model/Folder"

**Comment by LagoLunatic** [comment]
You need to type `pack_player`, then `-link`, then drag and drop the Link Original folder, then `-custom`, then drag and drop the Custom Model folder.
All separated by spaces.

**Comment by LagoLunatic** [comment]
And for the record, the order of the arguments *does* matter. Putting custom before link doesn't work.
