### ISSUE TITLE
SuperBDM not found?

### ISSUE THREAD

**Issue by Vicousvern** [LagoLunatic/ww_model_helpers#10]
![Untitled-1](https://user-images.githubusercontent.com/16777995/80872172-346a5680-8ca8-11ea-9c36-2a8b0f0751d1.jpg)

SuperBDM not located, even though the structure set up correctly. Would appreciate a fix or info as to whats going on please.

**Comment by LagoLunatic** [comment]
It's SuperBMD, not SuperBDM
