### ISSUE TITLE
unidentifiable importing issue

### ISSUE THREAD

**Issue by Jameriquiah** [LagoLunatic/ww_model_helpers#13]
tried to import custom model and it gave me this for some reason, the model is structured identically to the original so i am not quite sure what is going wrong here

![Untitled](https://user-images.githubusercontent.com/42100286/228565033-65246bf8-e439-4ee1-a4db-22d3471557d9.png)

**Comment by LagoLunatic** [comment]
It looks like you're using Yoshi's version of SuperBMD. Use my version which is linked in the readme: https://github.com/LagoLunatic/SuperBMD/releases/latest

**Comment by Jameriquiah** [comment]
when i use yours it just creates a Kmdl.arc that for some reason has a bigger file size than the original but all the models remain unchanged. so when i put the file in the game nothing changes

**Comment by LagoLunatic** [comment]
> for some reason has a bigger file size than the original

That's normal and not a problem, the original was compressed and my script doesn't recompress it.

> Kmdl.arc

So you're editing TP, not WW? Then I don't know anything, my tools are intended for WW player models only. Ask someone who has edited TP player models.
