### ISSUE TITLE
Can't extract models - file not found exception

### ISSUE THREAD

**Issue by PewnyPL** [LagoLunatic/ww_model_helpers#2]
Whenever I try to run extract_models.exe it extracts the bone animations folder, then extracts binfairy.bdl. At this point I get an exception thrown by SuperBMD:
`Unhandled exception: System.IO.FileNotFoundException: Filename was null or could not be found`
`   in Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)`
`   in SuperBMD.Model.Load(String filePath)`
`   in SuperBMD_UnitTest.Program.Main(String[] args)`

Running the file manually with SuperBMD works fine. I modified the source of extract_models.py and ran it in python. The modification was as follows, near end of model or texture extractiong function:
`else:`
`    superbmd_folder = "SuperBMD"`
`    print("Extracting model %s" % output_file_name)`
`    command = [`
`      os.path.join(superbmd_folder, "SuperBMD.exe"),`
`      "-i", output_file_name,`
`    ]`
`    print("Extracting model %s" % command)`

Just a couple of simple prints, one that shows what the "output_file_name" is and another that shows what the "command" is. This is the output:

`Extracting model C:\WindWaker\WWModelHelper3\LinkOrg\binfairy\binfairy.bdl`
`Extracting model ['SuperBMD\\SuperBMD.exe', '-i',` `'C:\\WindWaker\\WWModelHelper3\\LinkOrg\\binfairy\\binfairy.bdl']`
I'm not sure what exactly does it, but for some reason the backslashes get doubled upon constructing the command and this is confusing SuperBMD. I tried to call the script and giving the location of Link.arc with forward slashes, ie 
`py .\extract_models.py C:/WindWaker/WWModelHelper3/LinkOrg/Link.arc`
but the output is as follows:
`Extracting model C:/WindWaker/WWModelHelper3/LinkOrg\binfairy\binfairy.bdl`
`Extracting model ['SuperBMD\\SuperBMD.exe', '-i', 'C:/WindWaker/WWModelHelper3/LinkOrg\\binfairy\\binfairy.bdl']`
The main part of the string stays fine, with single slashes, but anything added by the script gets double backslashes.

**Comment by LagoLunatic** [comment]
>I'm not sure what exactly does it, but for some reason the backslashes get doubled upon constructing the command and this is confusing SuperBMD.

No, the backslashes are singular. They only look double because you printed them in a way that python displays the string as escaped.

What version of SuperBMD are you using? v1.2? If so, v1.2 will interpret the command:
`superbmd.exe -i C:\WindWaker\WWModelHelper3\LinkOrg\binfairy\binfairy.bdl`
In such a way that it thinks `-i` is the file path, since the command format was changed after v1.2, and it says the file isn't found because there's no file at the path `-i` on your hard drive.

Download the latest version from my fork, v1.3.3: https://github.com/LagoLunatic/SuperBMD/releases

**Comment by PewnyPL** [comment]
Oh yeah... I did try it with v1.1 as well and still got the error. I just checked and when I ran the command manually I didn't use the -i switch, with it the command does not work either. Welp, my bad then.
