### ISSUE TITLE
Trouble extracting models from link.arc

### ISSUE THREAD

**Issue by pkmnlovr74** [LagoLunatic/ww_model_helpers#3]
When I try to extract models from link.arc, I get the following:
Extracting animation atngsha.bck
Extracting animation bomb.bck
Extracting animation combo_tate.bck
Extracting animation gicer01.bck
Extracting animation gwp00.bck
Extracting animation swgripmsab.bck
Extracting animation yuchw00.bck
Extracting model binfairy.bdl

Unhandled Exception: Assimp.AssimpException: Error loading unmanaged library from path: Assimp32.dll, see inner exception for details.
The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   --- End of inner exception stack trace ---
   at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   at Assimp.Unmanaged.AssimpLibrary.GetExportFormatDescriptions()
   at Assimp.AssimpContext.TestIfExportIdIsValid(String exportFormatId)
   at Assimp.AssimpContext.ExportFile(Scene scene, String fileName, String exportFormatId, PostProcessSteps preProcessing)
   at SuperBMDLib.Model.ExportAssImp(String fileName, String modelType, ExportSettings settings)
   at SuperBMDLib.Program.Main(String[] args)

I have no idea what this means or what I can do, anything I can do to fix this? Any help is greatly appreciated

**Comment by LagoLunatic** [comment]
Look inside your SuperBMD folder. The one with SuperBMD.exe inside it. There should be 11 files in total there, and 1 of them should be called Assimp32.dll. If Assimp32.dll is not there, you must have deleted it or moved it accidentally.

**Comment by pkmnlovr74** [comment]
It's there. I have all 11 files in the SuperBMD folder

**Comment by LagoLunatic** [comment]
If you try to run superbmd.exe itself directly (not using extract_models.exe) I assume you get the exact same error?

**Comment by pkmnlovr74** [comment]
No. I get the message:
Unhandeled Exception: System.Exception: Unknown parameter "C:\Users\Name\Downloads\WW_Model_helpers_1.2.2\SuperBMD\Link.arc"
at SuperBMDLib.Arguments..ctor(String[] args)
at SuperBMDLib.Program.Main(String[] args)

**Comment by LagoLunatic** [comment]
You need to run superbmd like this:
`superbmd -i path/to/model.bdl`
It won't work on link.arc directly.
If you look in the binfairy folder, there should be a binfairy.bdl you can use.

**Comment by LagoLunatic** [comment]
By the way, judging by the path "C:\Users\Name\Downloads\WW_Model_helpers_1.2.2\SuperBMD\Link.arc", you put Link.arc inside your SuperBMD folder? I'm not sure if that's the cause of your current issue or not, but you should probably avoid doing that either way.

**Comment by pkmnlovr74** [comment]
I apologize, I'm not really following well. I was really confused by your tutorial and I get stuck. What do you mean by using the binfairy?

**Comment by LagoLunatic** [comment]
Like I said, you need to give superbmd a .bdl file for it to run. Since you tried to run extract_models.exe, binfairy.bdl is the only bdl it would have gotten out of the link.arc. So you can use that to test superbmd out and see if it runs directly.

I have no clue at all what your issue is though. I'm just guessing it's likely unrelated to the helper scripts and some kind of incompatibility between superbmd and your computer is, but who knows.

**Comment by pkmnlovr74** [comment]
I get the same error

**Comment by LagoLunatic** [comment]
Then yeah, doubt I can do anything about this. Only thing I can recommend is to go in the #cosmetic-mods channel of the rando discord and ask if anybody there has seen the same error you have.

**Comment by pkmnlovr74** [comment]
I ran it on a different computer and it worked
