### ISSUE TITLE
I can't run the fix normals script!

### ISSUE THREAD

**Issue by M3KAI5ER44** [LagoLunatic/ww_model_helpers#5]
I can't run the fix normals script in blender it just says to check console.

**Comment by LagoLunatic** [comment]
Blender shows python errors in the system console, accessible via window -> toggle system console

**Comment by M3KAI5ER44** [comment]
"Traceback (most recent call last):
  File "C:\Users\m3kai\Documents\Wind Waker WideScreen Dump\cl.blend\fix_normals.py", line 11, in <module>
AttributeError: 'Object' object has no attribute 'select'
Error: Python script failed, check the message in the system console"
I am a beginner to this so as far as I know, I think I might be doing something wrong?

**Comment by LagoLunatic** [comment]
It sounds like you're using blender 2.8. As mentioned in the readme, blender 2.8 is not yet supported. It completely changed the python scripting api so I have to basically rewrite the scripts from scratch for it.

But I am almost done with that, the only one I'm not finished with is generate_previews.py. So for now, I added the blender 2.8 scripts I am done with here so you can use them: <https://github.com/LagoLunatic/ww_model_helpers/tree/master/blender%202.8>
I'll finish generate_previews.py at some point in the next few days and officially release an update.

I also updated the readme with information about blender 2.8: <https://github.com/LagoLunatic/ww_model_helpers/blob/master/README.md>
Especially note this part:
>Open Blender, delete all default objects in the scene, and go to File -> Import -> Collada (.dae).
>**Important note: If using Blender 2.8, you must check the checkbox saying "Keep Bind Info" under import settings.**

If you already imported a model without doing that, start over.

**Comment by M3KAI5ER44** [comment]
Thanks! You made my day!
