### ISSUE TITLE
Umm... I can't pack the file.

### ISSUE THREAD

**Issue by M3KAI5ER44** [LagoLunatic/ww_model_helpers#6]
This time I really have no idea what happened.
"Unhandled Exception: System.Exception: Number of meshes (25) is not the same as the number of mesh objects (49); cannot sort.
Mesh objects: mesh-0, mesh-1, mesh-2, mesh-3, mesh-4, mesh-5, mesh-6, mesh-7, mesh-8, mesh-9, mesh-10, mesh-11, mesh-12, mesh-13, mesh-14, mesh-15, mesh-16, mesh-17, mesh-18, mesh-19, mesh-20, mesh-21, mesh-22, mesh-23, mesh-0.001, mesh-0, mesh-1, mesh-2, mesh-3, mesh-4, mesh-5, mesh-6, mesh-7, mesh-8, mesh-9, mesh-10, mesh-11, mesh-12, mesh-13, mesh-14, mesh-15, mesh-16, mesh-17, mesh-18, mesh-19, mesh-20, mesh-21, mesh-22, mesh-23
Meshes: meshId0_name, meshId1_name, meshId2_name, meshId3_name, meshId4_name, meshId5_name, meshId6_name, meshId7_name, meshId8_name, meshId9_name, meshId10_name, meshId11_name, meshId12_name, meshId13_name, meshId14_name, meshId15_name, meshId16_name, meshId17_name, meshId18_name, meshId19_name, meshId20_name, meshId21_name, meshId22_name, meshId23_name, meshId0_name.001
   at SuperBMDLib.Model.SortMeshesByObjectNames(Scene scene)
   at SuperBMDLib.Model..ctor(Scene scene, Arguments args)
   at SuperBMDLib.Model.Load(Arguments args)
   at SuperBMDLib.Program.Main(String[] args)"

**Comment by LagoLunatic** [comment]
>Mesh objects: mesh-0, mesh-1, mesh-2, mesh-3, mesh-4, mesh-5, mesh-6, mesh-7, mesh-8, mesh-9, mesh-10, mesh-11, mesh-12, mesh-13, mesh-14, mesh-15, mesh-16, mesh-17, mesh-18, mesh-19, mesh-20, mesh-21, mesh-22, mesh-23, mesh-0.001, mesh-0, mesh-1, mesh-2, mesh-3, mesh-4, mesh-5, mesh-6, mesh-7, mesh-8, mesh-9, mesh-10, mesh-11, mesh-12, mesh-13, mesh-14, mesh-15, mesh-16, mesh-17, mesh-18, mesh-19, mesh-20, mesh-21, mesh-22, mesh-23

cl.bdl has 24 mesh objects (mesh-0 to mesh-23), it looks like you created a shitload of new objects which will not work. You can't modify the way the model is laid out like that or it wouldn't load ingame even if it did pack.

Also I recommend joining the rando discord server, all discussion about custom models happens in #cosmetic-mods there so you'd get better help there

**Comment by M3KAI5ER44** [comment]
All I did was add casual hair and the fix normals thing.
