### ISSUE TITLE
unpack_models.exe and pack_models.exe closing down

### ISSUE THREAD

**Issue by ScagsTheDove** [LagoLunatic/ww_model_helpers#7]
Greetings

I have been following the guide and got to the point where i have to execute the unpack_models.exe program but it doesnt seem to work. It opens up the command prompt then flashes some text for a split second then closes down. I managed to make out the first lines first word which is Invalid and something about models. I ran the net framework installer but it said its already installed. I reinstalled the models folder and placed it next to the exe files but nothing changed. I had problems before with these types of files because they where in admin folders, but i dont think thats the case. Running as admin doesnt change anything either. Either way thank you for reading and i hope i get a solution soon. (sorry if i posted this in a wrong place, im farely new to this platform as more than downloads)

**Comment by LagoLunatic** [comment]
That's just how all command line programs work if you double click on them. Look up a guide on how to use the command prompt online or ask someone else who knows how to use it, I don't want to explain it.
