### ISSUE TITLE
Can't unpack the file

### ISSUE THREAD

**Issue by JK0JK** [LagoLunatic/ww_model_helpers#8]
Terribly sorry for this. I figure you're tired of reading stuff like this for more than a year.

I downloaded and extracted SuperBMD.zip and put the resulting folder inside the ww_mod_helpers directory.

Then I ran the command `cd C:\path\to\ww_mod_helpers` to then run `unpack_models.py "path/to/Link Original/Link.arc"`. Without the first command, it wouldn't recognize unpack_models.exe or .py and there are no .exe files to be found, despite the instructions.

Now he did try to read the .py file (good thing I have python 3.8 installed on my pc) but there was a problem reading line 13.

`Traceback (most recent call last):
  File "C:\path\to\ww_model_helpers\unpack_models.py", line 13, in <module>
    from wwlib.rarc import RARC
ModuleNotFoundError: No module named 'wwlib'`

What should I do?

**Comment by LagoLunatic** [comment]
> there are no .exe files to be found, despite the instructions.

You didn't read the very first line of the instructions.

> ## Getting set up
> 
> First download and extract the helper scripts: https://github.com/LagoLunatic/ww_model_helpers/releases/latest

You tried to run them from source.

**Comment by JK0JK** [comment]
Thanks!
It would seem I was also using an outdated version of SuperBMD so taking a step back helped a lot.
